# Generated by Django 5.1.1 on 2024-09-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
